version: '3.8'

services:
  web:
    build:
      context: ./web  # Contexto da construção para a pasta web
      dockerfile: Dockerfile
    ports:
      - "80:80"

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: crud
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .  # Contexto da construção para a raiz do projeto, onde está o Dockerfile-nestjs
      dockerfile: Dockerfile-nestjs
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: ''
      DB_DATABASE: crud
    ports:
      - "3001:3000"

volumes:
  db_data:
